coeffects and capabilities
hhvm/hack-codegen pull request #142
Opened 2021-11-07 01:32 UTC by dienesl

the codegen didn't had coeffects support yet, when you/we didn't want to write a whole hacbuilder block only for it

2021-11-15 18:54 UTC, fredemmott requested changes
Requesting changes because of `string` vs `keyset<string>`; if you strongly feel that `string` is better, could you give some usecase examples?

2021-11-15 18:54 UTC, fredemmott commented on src/CodegenFunctionish.hack
> +  }
I don't think something like this should be needed, especially if it takes a keyset<string> - if there's a need for this, could you give an example?

2021-11-15 19:00 UTC, fredemmott commented
Please also extend the unit tests to cover this :)

2021-11-16 02:30 UTC, dienesl commented
i've followed your instructions and i've patched these. thank you!

2021-11-17 21:37 UTC, merged